### ISSUE TITLE
AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/unity3d/player/UnityPlayerActivity

### ISSUE THREAD

**Issue by jeffcrouse** [kshoji/Unity-MIDI-Plugin-supports#37]
**Steps to reproduce error**
1. Create a Unity project with Unity 60000.0.43f1
2. Player Settings -> Active Input Handling = Old
3. Remove "Input System" from package manager
4. Switch build platform to Android
5. Player Settings -> Minimum API Level: Android 12
6. Player Settings -> Internet Access: Require
7. Import "MIDI Plugin for Mobile and Desktop 2.0.0" from package manager
8. Add MidiSampleScene to Scene List and uncheck default Sample Scene
9. Choose my Galaxy Tab A7 running Android Version 12 under "Run Device"
10. Enable Development Build
11. Build and Run

**What do I expect to see**
A bunch of GUI windows, as seen in MidiSampleScene::OnGUIWindow

**What do I actually see**
![Image](https://github.com/user-attachments/assets/67c61786-9986-41e9-ad48-b29ac02b2551)
The 

**Other Information**
- I can compile and deploy Android apps WITHOUT the MIDI plugin just fine. 
- I am only using RTP MIDI, so I don't need any of the Bluetooth stuff
- At some point, I managed to get something working by removing MIDI\Scripts\Editor folder, but since upgrading to 2.0.0, I can't seem to get it running at all anymore.

**Comment by kshoji** [comment]
@jeffcrouse 
Sorry for the late reply. I finally have some time to work on it.

I looked into this issue.
This seems to be happening because when a new feature called `GameActivity` is enabled, an unexpected Activity is called at startup.

I plan to fix this issue in the next version, but if you want to fix it on the current version, try changing "Other Settings > Configuration > Application Entry Point" so that only "Activity" is selected, as described in the document below.

https://docs.unity3d.com/6000.0/Documentation/Manual/android-application-entries-set.html

**Comment by kshoji** [comment]
This issue appears to occur when both `GameActivity` and `Bluetooth MIDI` functions are enabled.

If you do not need Bluetooth and want to keep the GameActivity function enabled, deleting the `Assets/MIDI/Plugins/Android/ble-midi-0.0.19.aar` file will resolve the issue.

**Comment by kshoji** [comment]
It seems that it is not possible to have both GameActivity and Bluetooth functionality, I will add a note to the documentation.
